export const dummyData = [
  {
    wordId: "1",
    word: "book",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "2",
    word: "free",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "3",
    word: "disclaimer",
    type: "noun",
    definition:
      "Donec vel facilisis eros. Sed molestie, orci sed mattis vulputate, mi purus pulvinar lacus, eu dapibus lectus mi ut augue.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "4",
    word: "example",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Donec porttitor eros ut nisi",
  },
  {
    wordId: "5",
    word: "song",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "6",
    word: "plane",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "7",
    word: "hooks",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "8",
    word: "class",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
  {
    wordId: "9",
    word: "otherwise",
    type: "noun",
    definition: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    example: "Nullam efficitur ornare nulla nec finibus.",
  },
];
